### ISSUE TITLE
Serial simulator - Windows 10 - Port detection fails.

### ISSUE THREAD

**Issue by MCS-Tech** [panaaj/nmeasimulator#24] opened 2021-02-17 14:42 UTC
Hi,
Testing with serial output, the application detects incorrect COM port available in Windows. 
I am running a Win10Pro64 computer, latest release Win10. 
COM port is by MOXA UPort1150i USB to serial (industrial, high quality device). 
Windows shows the COM port to be COM5. The simulator misses this by 1 and detects COM6.
Opening COM6 fails (of course) as this this port does not exist on my computer. 
I am not able to force it to COM5 as only "detected" ports are available.

The same adapter works with all my other simulators, so this issue must be related to this application.
All other applications detects correctly COM5.

![Clipboard011](https://user-images.githubusercontent.com/64583025/108219851-66b14b80-7136-11eb-8ad7-7d5083ff1590.jpg)

**Comment by panaaj** [comment] 2021-02-18 05:17
The list of serial ports and their names comes from a serialport library.
If the issue is related to the library and this USB serial device (which I do not have) you will have to run a test on your device.

Not sure how comfortable you are with using npm / node to try testing?
With nodejs installed on your device run the command `npx @serialport/list` and check the output to see what is reported.

Documentation  [link](https://serialport.io/docs/guide-cli) included here for information.

**Comment by MCS-Tech** [comment] 2021-02-18 08:24
Hi,

The npx library documentation seems to focus on Linux?
I have run some commands in Windows PowerShell. And they all state COM5 as being correct (not COM6).
[cid:image005.jpg@01D705D7.DAF759F0]

[cid:image003.png@01D705D7.8E881730]

[cid:image004.png@01D705D7.8E881730]

The USB device I am using is a widely used, and high-quality unit. I have never had any issues with it over the years.
https://www.moxa.com/en/products/industrial-edge-connectivity/usb-to-serial-converters-usb-hubs/usb-to-serial-converters/uport-1100-series

Finding Laptop computers with physical/onboard serial ports are no longer an option.

All other software I have tested (I am using various simulators on a daily basis for system testing) is detecting COM5 as correct.
A possible workaround would be to allow manual input if autodetection fails?

Cheers,
Anders

**Comment by panaaj** [comment] 2021-02-18 09:50
Nodejs can be installed on Windows devices.... once installed you can open. Command prompt and run the `npx @serialport/list` command.

**Comment by MCS-Tech** [comment] 2021-02-18 10:13
Hi,

Installed and tested.
It incorrectly detects COM6

[cid:image001.png@01D705E7.1CB50A90]

Cheers,
Anders

**Comment by panaaj** [comment] 2021-02-18 10:16
Might want to log an issue with them.

**Comment by MCS-Tech** [comment] 2021-02-18 10:32
Hi,

I think you need to do that.
This is preventing me from using your otherwise excellent simulator in serial mode.

Cheers,
Anders

**Comment by MCS-Tech** [comment] 2021-02-23 14:55
Hi,

A simple (?) workaround would maybe be to make the COM port selection open for manual input?
Then the "detect ports" could be used when it is back in operation?

Cheers,
Anders

**Comment by panaaj** [comment] 2021-02-24 06:04
I will look to add manual input for COM port paths in the next release.

**Comment by cyferc** [comment] 2021-03-15 02:11
Yes please make serial port selection a manual text box entry. On linux I would like to use a virtual serial port created by socat but it's not detected. I'm trying to loopback the data into my app but can't. 

Your app is really nice otherwise!

**Comment by panaaj** [comment] 2021-03-15 04:38
This feature is in the next release.

**Comment by panaaj** [comment] 2021-03-17 05:46
closed by v1.2.0

**Closed by panaaj** 2021-03-17 05:46 UTC

**Comment by cyferc** [comment] 2021-03-19 03:49
Works great thanks!
